# Generated by Django 3.1.7 on 2021-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('True', 'Ок'), ('False', 'Ошибка')], max_length=10),
        ),
    ]
